from typing import List, Optional

class StemResult:
    original: str
    root: str
    confidence: float
    operation: str
    in_dictionary: bool

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class FuzzyMatch:
    word: str
    distance: int

    def __repr__(self) -> str: ...

class MalagasyStemmer:
    def __init__(self) -> None: ...
    def stem(self, word: str) -> str: ...
    def stem_with_details(self, word: str) -> StemResult: ...
    def stem_batch(self, words: List[str]) -> List[str]: ...
    def stem_batch_with_details(self, words: List[str]) -> List[StemResult]: ...

def stem(word: str) -> str: ...
def stem_with_details(word: str) -> StemResult: ...
def tokenize(text: str) -> List[str]: ...
def tokenize_and_stem(text: str, remove_stopwords: bool = True) -> List[str]: ...
def tokenize_and_stem_with_details(text: str, remove_stopwords: bool = True) -> List[StemResult]: ...
def is_stopword(word: str) -> bool: ...
def fuzzy_root_lookup(word: str, max_distance: int = 1) -> List[FuzzyMatch]: ...
